// site/src/examples/js/vue_component_display_code.vue
<script setup>
  import IntlTelInput from "intl-tel-input/vue";
  import "intl-tel-input/styles";

  const number = ref("");
  const isValid = ref(false);
  const errorCode = ref(0);
  const noticeMode = ref("off");

  const notice = computed(() => {
    // Logic to determine the notice message based on the current state
  });

  const handleSubmit = () => {
    noticeMode.value = "submit";
  };

  const handleBlur = () => {
    noticeMode.value = "blur";
  };
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <IntlTelInput
      @changeNumber="number = $event"
      @changeValidity="isValid = $event"
      @changeErrorCode="errorCode = $event"
      :initOptions="{
        initialCountry: 'us',
        loadUtils: () => import('intl-tel-input/utils'),
      }"
      :inputProps="{
        onBlur: handleBlur,
      }"
    />
    <button type="submit">Validate</button>
    <div v-if="notice" class="notice">{{ notice }}</div>
  </form>
</template>

// site/src/examples/js/angular_component_display_code.js
import { Component, ViewChild } from "@angular/core";
import {
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from "@angular/forms";
import { IntlTelInputComponent } from "intl-tel-input/angular";
import "intl-tel-input/styles";

@Component({
  selector: "#app",
  template: `
    <form [formGroup]="fg" (ngSubmit)="handleSubmit()">
      <intl-tel-input
        #telInput
        formControlName="phone"
        name="phone"
        [initOptions]="initOptions"
      />
      <button type="submit">Validate</button>
      <div class="notice">{{ noticeText }}</div>
    </form>
  `,
  standalone: true,
  imports: [IntlTelInputComponent, ReactiveFormsModule],
})
export class AppComponent {
  @ViewChild("telInput") telInput;
  hasValidated = false;

  initOptions = {
    initialCountry: "us",
    loadUtils: () => import("intl-tel-input/utils"),
  };

  fg = new FormGroup({
    phone: new FormControl()<string>("", [Validators.required]),
  });

  get phone() {
    return this.fg.get("phone");
  }

  get noticeText() {
    // Determine the notice message based on the current state
  }

  handleSubmit() {
    this.phone?.markAsTouched();
    this.hasValidated = true;
  }
}
