// site/src/examples/js/react_component_display_code.js
import React, { useMemo, useState } from "react";
import IntlTelInput from "intl-tel-input/react";
import "intl-tel-input/styles";

const App = () => {
  const [number, setNumber] = useState("");
  const [isValid, setIsValid] = useState(false);
  const [errorCode, setErrorCode] = useState(0);
  const [noticeMode, setNoticeMode] = useState("off");

  const notice = useMemo(() => {
    // Logic to determine the notice based on the validation result
  }, [noticeMode, isValid, number, errorCode]);

  const handleSubmit = (e) => {
    e.preventDefault();
    setNoticeMode("submit");
  };

  return (
    <form onSubmit={handleSubmit}>
      <IntlTelInput
        onChangeNumber={setNumber}
        onChangeValidity={setIsValid}
        onChangeErrorCode={setErrorCode}
        initOptions={{
          initialCountry: "us",
          loadUtils: () => import("intl-tel-input/utils"),
        }}
        inputProps={{
          name: "phone",
          onBlur: () => setNoticeMode("blur"),
        }}
      />
      <button type="submit">Validate</button>
      {notice && <div className="notice">{notice}</div>}
    </form>
  );
};
export default App;

// site/src/examples/js/angular_component_display_code.ts
import { Component, ViewChild } from "@angular/core";
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from "@angular/forms";
import IntlTelInput from "intl-tel-input/angular";
import "intl-tel-input/styles";

@Component({
  selector: "#app",
  template: `
    <form [formGroup]="fg" (ngSubmit)="handleSubmit()">
      <intl-tel-input
        #telInput
        formControlName="phone"
        name="phone"
        [initOptions]="initOptions"
      />
      <button type="submit">Validate</button>
      <div class="notice">
        <!-- Logic to determine the notice based on the validation result -->
      </div>
    </form>
  `,
  standalone: true,
  imports: [IntlTelInput, ReactiveFormsModule],
})
export class AppComponent {
  @ViewChild("telInput") telInput!: IntlTelInput;

  initOptions = {
    initialCountry: "us",
    loadUtils: () => import("intl-tel-input/utils"),
  };

  fg: FormGroup = new FormGroup({
    phone: new FormControl<string>("", [Validators.required]),
  });

  notice: string | null = null;

  get phone() {
    return this.fg.get("phone");
  }

  handleSubmit(): void {
    this.phone?.markAsTouched();
    if (this.fg.valid) {
      this.notice = `Valid number: ${this.telInput.getInstance()?.getNumber()}`;
    }
  }
}
