// site/src/examples/js/vue_component_display_code.vue
<script setup>
  import IntlTelInput from "intl-tel-input/vue";
  import "intl-tel-input/styles";

  const number = ref("");
  const isValid = ref(false);
  const errorCode = ref(0);
  const noticeMode = ref("off");

  const notice = computed(() => {
    // Logic to determine the notice message based on the current state
  });

  const handleSubmit = () => {
    noticeMode.value = "submit";
  };

  const handleBlur = () => {
    noticeMode.value = "blur";
  };
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <IntlTelInput
      @changeNumber="number = $event"
      @changeValidity="isValid = $event"
      @changeErrorCode="errorCode = $event"
      :options="{
        initialCountry: 'us',
        loadUtils: () => import('intl-tel-input/utils'),
      }"
      :inputProps="{
        onBlur: handleBlur,
      }"
    />
    <button type="submit">Validate</button>
    <div v-if="notice" class="notice">{{ notice }}</div>
  </form>
</template>

// site/src/examples/js/svelte_component_display_code.svelte
<script>
  import IntlTelInput from "intl-tel-input/svelteWithUtils";
  import "intl-tel-input/styles";

  let number = $state("");
  let isValid = $state(false);
  let errorCode = $state(0);
  let noticeMode = $state("off");

  const notice = $derived.by(() => {
    // Determine the notice message based on the current state
  });

  const handleSubmit = (event) => {
    event.preventDefault();
    noticeMode = "submit";
  };
</script>

<form onsubmit={handleSubmit}>
  <IntlTelInput
    onChangeNumber={(n) => (number = n)}
    onChangeValidity={(v) => (isValid = v)}
    onChangeErrorCode={(e) => (errorCode = e)}
    options={{
      initialCountry: "us",
      loadUtils: () => import("intl-tel-input/utils"),
    }}
    inputProps={{
      onblur: () => (noticeMode = "blur"),
    }}
  />
  <button type="submit">Validate</button>
  {#if notice}
    <div class="notice">{notice}</div>
  {/if}
</form>
