// site/src/examples/js/react_component_display_code.js
import React, { useMemo, useState } from "react";
import IntlTelInput from "intl-tel-input/react";
import "intl-tel-input/styles";

const App = () => {
  const [number, setNumber] = useState("");
  const [isValid, setIsValid] = useState(false);
  const [errorCode, setErrorCode] = useState(0);
  const [noticeMode, setNoticeMode] = useState("off");

  const notice = useMemo(() => {
    // Logic to determine the notice based on the validation result
  }, [noticeMode, isValid, number, errorCode]);

  const handleSubmit = (e) => {
    e.preventDefault();
    setNoticeMode("submit");
  };

  return (
    <form onSubmit={handleSubmit}>
      <IntlTelInput
        onChangeNumber={setNumber}
        onChangeValidity={setIsValid}
        onChangeErrorCode={setErrorCode}
        initialCountry="us"
        loadUtils={() => import("intl-tel-input/utils")}
        inputProps={{
          name: "phone",
          onBlur: () => setNoticeMode("blur"),
        }}
      />
      <button type="submit">Validate</button>
      {notice && <div className="notice">{notice}</div>}
    </form>
  );
};
export default App;

// site/src/examples/js/svelte_component_display_code.svelte
<script>
  import IntlTelInput from "intl-tel-input/svelteWithUtils";
  import "intl-tel-input/styles";

  let number = $state("");
  let isValid = $state(false);
  let errorCode = $state(0);
  let noticeMode = $state("off");

  const notice = $derived.by(() => {
    // Determine the notice message based on the current state
  });

  const handleSubmit = (event) => {
    event.preventDefault();
    noticeMode = "submit";
  };
</script>

<form onsubmit={handleSubmit}>
  <IntlTelInput
    onChangeNumber={(n) => (number = n)}
    onChangeValidity={(v) => (isValid = v)}
    onChangeErrorCode={(e) => (errorCode = e)}
    options={{
      initialCountry: "us",
      loadUtils: () => import("intl-tel-input/utils"),
    }}
    inputProps={{
      onblur: () => (noticeMode = "blur"),
    }}
  />
  <button type="submit">Validate</button>
  {#if notice}
    <div class="notice">{notice}</div>
  {/if}
</form>
