// vue/src/IntlTelInput.vue
<script setup lang="ts">
import intlTelInput from "./intl-tel-input";
import type { SomeOptions } from "./modules/types/public-api";
import { onMounted, onUnmounted, ref, watch, computed } from "vue";
import type { InputHTMLAttributes } from "vue";

interface Props {
  options?: SomeOptions;
  usePreciseValidation?: boolean;
  disabled?: boolean;
  inputProps?: InputHTMLAttributes;
  value?: string | null;
  modelValue?: string | null;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
  usePreciseValidation: false,
  inputProps: () => ({}),
  options: () => ({}),
});

defineOptions({ inheritAttrs: false });

const emit = defineEmits([
  "changeNumber",
  "changeCountry",
  "changeValidity",
  "changeErrorCode",
  "update:modelValue",
]);

const displayed = computed(() => props.value ?? props.modelValue ?? "");

const input = ref<HTMLInputElement | null>(null);
const instance = ref<ReturnType<typeof intlTelInput> | null>(null);
const lastEmittedNumber = ref<string>();
const lastEmittedCountry = ref<string>();
const lastEmittedValidity = ref<boolean>();
const lastEmittedErrorCode = ref<number | null>();

const isValid = () => {
  if (instance.value) {
    return props.usePreciseValidation
      ? instance.value.isValidNumberPrecise()
      : instance.value.isValidNumber();
  }

  return null;
};

const updateValidity = () => {
  const isCurrentlyValid = isValid();
  if (isCurrentlyValid === null) return;

  const valid = !!isCurrentlyValid;
  const errorCode = valid
    ? null
    : instance.value?.getValidationError?.() ?? null;

  if (valid !== lastEmittedValidity.value) {
    lastEmittedValidity.value = valid;
    emit("changeValidity", valid);
  }

  if (errorCode !== lastEmittedErrorCode.value) {
    lastEmittedErrorCode.value = errorCode;
    emit("changeErrorCode", errorCode);
  }
};

const updateValue = () => {
  const number = instance.value?.getNumber() ?? "";

  if (number !== lastEmittedNumber.value) {
    lastEmittedNumber.value = number;
    emit("changeNumber", number);
    emit("update:modelValue", number);
  }

  updateValidity();
};

const updateCountry = () => {
  const country = instance.value?.getSelectedCountryData().iso2 ?? "";
  if (country !== lastEmittedCountry.value) {
    lastEmittedCountry.value = country;
    emit("changeCountry", country);
  }
  updateValue();
};

onMounted(() => {
  if (input.value) {
    instance.value = intlTelInput(input.value, props.options);

    if (displayed.value) {
      instance.value.setNumber(displayed.value);
    }

    if (props.disabled) {
      instance.value.setDisabled(props.disabled);
    }

    lastEmittedNumber.value = instance.value.getNumber?.() ?? "";
    lastEmittedCountry.value = instance.value.getSelectedCountryData().iso2 ?? "";

    const initialValid = isValid();
    if (initialValid !== null) {
      lastEmittedValidity.value = !!initialValid;
      lastEmittedErrorCode.value = initialValid
        ? null
        : instance.value.getValidationError?.() ?? null;
    }
  }
});

watch(
  () => props.disabled,
  (newValue) => instance.value?.setDisabled(newValue),
);

watch(
  () => displayed.value,
  (val) => {
    if (!instance.value) return;

    // Avoid cursor jumping when typing
    const next = val ?? "";
    const currentCanonical = instance.value.getNumber?.() ?? "";
    const isFocused = document.activeElement === input.value;

    if (isFocused || currentCanonical === next) return;

    instance.value.setNumber(next);
    updateValidity();
  },
  { flush: "post" },
)

onUnmounted(() => instance.value?.destroy());

defineExpose({ instance, input });
</script>

<template>
  <input
    ref="input"
    type="tel"
    @countrychange="updateCountry"
    @input="updateValue"
    v-bind="inputProps"
  />
</template>

// svelte/src/intl-tel-input/IntlTelInput.svelte
<script lang="ts">
  import intlTelInput from "../intl-tel-input";
  import type { Iti } from "../intl-tel-input";
  import type { SomeOptions } from "../modules/types/public-api";
  import { onMount, onDestroy } from "svelte";

  // Props
  let {
    disabled = false,
    inputProps = {},
    options = {},
    usePreciseValidation = false,
    value = "",
    onChangeNumber,
    onChangeCountry,
    onChangeValidity,
    onChangeErrorCode,
  }: {
    disabled?: boolean;
    inputProps?: Record<string, unknown>;
    options?: SomeOptions;
    value?: string;
    usePreciseValidation?: boolean;
    onChangeNumber?: (number: string) => void;
    onChangeCountry?: (country: string) => void;
    onChangeValidity?: (valid: boolean) => void;
    onChangeErrorCode?: (errorCode: number | null) => void;
  } = $props();

  // State
  let inputElement: HTMLInputElement | undefined = $state();
  let instance: Iti | undefined = $state();
  let lastEmittedNumber: string | undefined = $state();
  let lastEmittedCountry: string | undefined = $state();
  let lastEmittedValidity: boolean | undefined = $state();
  let lastEmittedErrorCode: number | null | undefined = $state();
  let hasInitialized = $state(false);

  // Validation helper
  const isValid = (): boolean | null => {
    if (!instance) return null;
    return usePreciseValidation
      ? instance.isValidNumberPrecise()
      : instance.isValidNumber();
  };

  // Update handlers
  const updateValidity = () => {
    if (!instance) return;
    const isCurrentlyValid = isValid();
    if (isCurrentlyValid === null) return;

    const valid = !!isCurrentlyValid;
    const errorCode = valid ? null : instance.getValidationError();

    if (valid !== lastEmittedValidity) {
      lastEmittedValidity = valid;
      onChangeValidity?.(valid);
    }

    if (errorCode !== lastEmittedErrorCode) {
      lastEmittedErrorCode = errorCode;
      onChangeErrorCode?.(errorCode);
    }
  };

  const updateValue = () => {
    const number = instance?.getNumber() ?? "";
    if (number !== lastEmittedNumber) {
      lastEmittedNumber = number;
      onChangeNumber?.(number);
    }
    updateValidity();
  };

  const updateCountry = () => {
    const country = instance?.getSelectedCountryData().iso2 ?? "";
    if (country !== lastEmittedCountry) {
      lastEmittedCountry = country;
      onChangeCountry?.(country);
    }
    updateValue();
  };

  // Lifecycle
  onMount(() => {
    if (inputElement) {
      instance = intlTelInput(inputElement, options);
      inputElement.addEventListener("countrychange", updateCountry);
      if (value) instance.setNumber(value);
      if (disabled) instance.setDisabled(disabled);

      lastEmittedNumber = instance.getNumber() ?? "";
      lastEmittedCountry = instance.getSelectedCountryData().iso2 ?? "";

      const initialValid = isValid();
      if (initialValid !== null) {
        lastEmittedValidity = !!initialValid;
        lastEmittedErrorCode = initialValid ? null : instance.getValidationError();
      }
      hasInitialized = true;
    }
  });

  onDestroy(() => {
    if (inputElement) {
      inputElement.removeEventListener("countrychange", updateCountry);
    }
    instance?.destroy();
  });

  // Watch disabled prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setDisabled(disabled);
    }
  });

  // Expose instance and input for parent access
  export function getInstance(): Iti | undefined {
    return instance;
  }
  export function getInput(): HTMLInputElement | undefined {
    return inputElement;
  }
</script>

<input
  bind:this={inputElement}
  type="tel"
  oninput={updateValue}
  {...inputProps}
/>
